config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    resources :checks, only: %i[create]
  end

  scope module: :web do
    root 'welcome#index'

    get 'auth/destroy', to: 'auth#destroy'
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    post 'auth/:provider', to: 'auth#request', as: :auth_request

    resources :repositories, only: %i[index show new create] do
      scope module: :repositories do
        resources :checks, only: %i[show create]
      end
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  extend Enumerize

  RUBY = :ruby
  JAVASCRIPT = :javascript

  belongs_to :user
  has_many :checks, dependent: :destroy

  validates :github_id, presence: true, uniqueness: true

  enumerize :language, in: [RUBY, JAVASCRIPT]
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository::Check < ApplicationRecord
  include CheckStateMachine

  belongs_to :repository, inverse_of: :checks, class_name: 'Repository'

  def pending?
    %w[finished failed].exclude?(aasm_state)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :repositories, dependent: :destroy

  validates :email, presence: true, uniqueness: true
end

app/controllers/api/application_controller.rb
# frozen_string_literal: true

class Api::ApplicationController < ApplicationController
end

app/controllers/api/checks_controller.rb
# frozen_string_literal: true

class Api::ChecksController < Api::ApplicationController
  skip_before_action :verify_authenticity_token

  GITHUB_EVENT_HEADER = 'X-GitHub-Event'
  PING_EVENT = 'ping'
  PUSH_EVENT = 'push'

  def create
    event_type = request.headers[GITHUB_EVENT_HEADER]
    case event_type
    when PING_EVENT
      handle_ping_event
    when PUSH_EVENT, nil # nil for check
      handle_push_event
    else
      render json: { error: t('webhooks.errors.event_not_implemented') }, status: :not_implemented
    end
  end

  private

  def handle_ping_event
    render json: { message: 'Ok', application: Rails.application.class.module_parent_name }, status: :ok
  end

  def handle_push_event
    repository = Repository.find_by(github_id: repository_params[:id])

    return render json: { error: t('webhooks.errors.repository_not_found') }, status: :not_found if repository.nil?

    check = repository.checks.new
    if perform_lint_check(check)
      render json: { message: t('webhooks.messages.check_created_successfully') }, status: :ok
    else
      render json: { error: t('webhooks.errors.lint_service_failed') }, status: :unprocessable_entity
    end
  end

  def perform_lint_check(check)
    check.save!
    LintCheckJob.perform_later(check.id)
    true
  rescue StandardError
    check.mark_as_failed!
    false
  end

  def repository_params
    params.require(:repository).permit(:id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/auth_controller.rb
# frozen_string_literal: true

class AuthController < ApplicationController
    def callback
      existing_user = User.find_or_create_by(email: auth[:info][:email])
      if existing_user.persisted?
        sign_in existing_user

        existing_user.nickname = auth[:info][:nickname]
        existing_user.name = auth[:info][:name]
        existing_user.email = auth[:info][:email]
        existing_user.image_url = auth[:info][:image]
        existing_user.token = auth[:credentials][:token]

        existing_user.save

        redirect_to root_path, flash: { success: t('.login_success') }
      else
        redirect_to root_path, flash: { danger: t('.login_error') }
      end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to root_path, flash: { success: t('.bye') }
    end
  
    private
  
    def auth
      request.env['omniauth.auth']
    end
  
    def sign_in(user)
      session[:user_id] = user.id
    end
  end

app/controllers/concerns/auth_concern.rb
# frozen_string_literal: true

module AuthConcern
  class NotAuthenticatedError < StandardError; end

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
    session.clear
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def signed_in?
    session[:user_id].present? && current_user.present?
  end

  def authenticate_user!
    return if signed_in?

    raise NotAuthenticatedError
  end
end

app/controllers/web/application_controller.rb
# frozen_string_literal: true

class Web::ApplicationController < ApplicationController
  helper_method :signed_in?, :current_user

  include AuthConcern
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized
  rescue_from NotAuthenticatedError, with: :not_authenticated

  private

  def not_authorized
    redirect_to root_path, flash: { warning: t('flash.application.not_authorized') }
  end

  def not_authenticated
    redirect_to root_path, flash: { warning: t('flash.application.not_authenticated') }
  end
end

app/controllers/web/auth_controller.rb
# frozen_string_literal: true

module Web
  class AuthController < Web::ApplicationController
    def callback
      user_info = request.env['omniauth.auth']
      email, nickname = user_info[:info].values_at(:email, :nickname)
      token = user_info['credentials']['token']
      user = User.find_or_initialize_by(email: email.downcase)
      user.update(nickname:, token:)

      sign_in user
      redirect_to root_path, flash: { success: t('flash.auth.success') }
    end

    def destroy
      sign_out
      redirect_to root_path, flash: { info: t('flash.auth.destroy') }
    end
  end
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

class Web::Repositories::ChecksController < Web::ApplicationController
  before_action :authenticate_user!

  def show
    @check = Repository::Check.find(params[:id])
    authorize @check
  end

  def create
    @check = current_repository.checks.new
    authorize @check
    @check.save!

    LintCheckJob.perform_later(@check.id)
    redirect_to current_repository, flash: { success: t('flash.checks.create') }
  rescue StandardError => e
    @check.fail!
    UserMailer.with(check: @check).failed.deliver_later
    flash[:danger] = t('flash.checks.create_error', message: e.message)
    redirect_to repository_path(current_repository)
  end

  private

  def current_repository
    Repository.find(params[:repository_id])
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

class Web::RepositoriesController < Web::ApplicationController
  before_action :authenticate_user!

  def index
    @repositories = current_user.repositories
  end

  def show
    @repository = current_user.repositories.find(params[:id])
  end

  def new
    @repository = Repository.new
    @repositories = OctokitService.get_remote_repositories(current_user)
  end

  def create
    @repository = current_user.repositories.find_or_initialize_by(repository_params)
    exist = @repository.persisted?

    @repository.save!

    SetupRepositoryJob.perform_later(repository_params[:github_id]) unless exist

    redirect_to repositories_path, flash: { info: t('flash.repositories.create') }
  rescue StandardError => _e
    flash.now[:danger] = t('flash.repositories.create_error')
    @repositories = OctokitService.get_remote_repositories(current_user)
    render :new, status: :unprocessable_entity
  end

  private

  def repository_params
    params.require(:repository).permit(:github_id)
  end
end

app/controllers/web/welcome_controller.rb
# frozen_string_literal: true

class Web::WelcomeController < Web::ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/repositories_helper.rb
# frozen_string_literal: true

module RepositoriesHelper
  def commit_link(repository_full_name, commit_id)
    return if commit_id.blank?

    link = "https://github.com/#{repository_full_name}/commit/#{commit_id}"
    link_to commit_id, link, target: '_blank', rel: 'noopener'
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RailsProject66
    meta[name='viewport' content='width=device-width,initial-scale=1']
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  body
    .container.mb-4.d-flex.flex-wrap.align-items-center.py-2.border-bottom
      = render 'layouts/shared/nav'
    .container.my-4
      = render 'layouts/shared/flash'
    .container.mt-4.border.shadow.bg-white.rounded-3.mb-4
      = yield

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  - flash.each do |type, msg|
    .alert.alert-dissmissible.fade.show.d-flex.justify-content-between class="alert-#{type.to_s}"
      = msg
      button.btn-close[type="button" data-bs-dismiss="alert" aria-label="Close"]

app/views/layouts/shared/_nav.html.slim
.navbar.navbar-expand-md.me-auto
  = link_to root_path, class: 'navbar-brand me-md-4' do
    i.bi.bi-sliders[style="font-size: 1,5rem; color: Black;"]
  ul.nav.flex-grow-1.me-auto.ms-2
    li.nav-item
      = link_to t('nav.main'), root_path, class: 'nav-link link-dark'
    - if signed_in?
      li.nav-item
        = link_to t('nav.repositories'), repositories_path, class: 'nav-link link-dark'
ul.nav
  .nav-item.me-2.d-flex
    - if signed_in?
      li.nav-item
        = link_to current_user.email, root_path, class: 'nav-link text-secondary'
      li.nav-item
        = link_to t('nav.sign_out'), auth_destroy_path, class: 'nav-link link-dark'
    - else
      = button_to auth_request_path('github'), method: :post, data: { turbo: false }, class: 'nav-link link-dark' do
        span.bi.bi-github.me-2
        = t('nav.sign_in')

app/views/repositories/show.html.slim
.container
  .p-4.align-items-center.border.shadow.bg-white.rounded-3
    .mb-4
      h1 = @repository.name

    = link_to t('repositories.links.check_repository'), repository_path(@repository), class: 'btn btn-primary mb-4'
    p
      strong.me-2 = t('repositories.attributes.name')
      = @repository.name
    p
      strong.me-2 = t('repositories.attributes.language')
      = @repository.language
    p
      strong.me-2 = t('repositories.attributes.created_at')
      = @repository.created_at
    p
      strong.me-2 = t('repositories.attributes.updated_at')
      = @repository.updated_at
    hr
    table.table.table-striped
      thead
        tr
          th = ''
          th = t('checks.show.table.head.aasm_state')
          th = t('checks.show.table.head.commit_id')
          th = t('checks.show.table.head.is_successful')
          th = t('checks.show.table.head.created_at')
      tbody
        - @checks&.each do |check|
          tr
            td = link_to check.id, repository_check_path(@repository, check)
            td = check.aasm.human_state
            td = link_to_check_commit(check) if check.commit_id
            td = t(check.passed)
            td = check.created_at

app/views/web/repositories/_check.slim
  tr
      td = link_to check.id, repository_check_path(check.repository, check)
      td = t("repo_check_states.#{check.aasm_state}")
      td = commit_link(repository_full_name, check.commit_id)
      td = check.passed
      td = l(check.created_at, format: :short_full)

app/views/web/repositories/_form.html.slim
= simple_form_for repository, url: repositories_path, method: :post do |f|
  - if repository.errors.any?
    div style='color: red'
      h2 = t('repositories.errors.create', count: repository.errors.count)
      ul
        - repository.errors.each do |error|
          li = error.full_message
  div
    = f.input :github_id, collection: repositories, input_html: { class: 'form-control' },
    label_html: { class: 'form-label mt-1 mb-0' }, required: true
  .mt-3
    = f.submit t('repositories.buttons.create'), class: 'btn btn-primary'

app/views/web/repositories/checks/_check_details.html.slim
table.table
  tbody
    tr
      td
        = t('checks.results.checked_at')
      td
        = l(@check.updated_at.localtime)
    tr
      td
        = t('checks.results.status')
      td
        = t("repo_check_states.#{@check.aasm_state}")
    tr
      td
        = t('checks.results.check_passed')
      td
        = @check.passed
    tr
      td
        = t('checks.results.offenses_count')
      td
        = @check.offenses_count
    tr
      td
        = t('checks.results.commit_id')
      td
        = commit_link(@check.repository.full_name, @check.commit_id)
    - check_results = @check.check_results
    == render partial: 'check_results', check: @check if check_results.present?

app/views/web/repositories/checks/_check_results.html.slim
table.table.table-hover.mb-5
  thead
    tr
      th
        = t('checks.results.message')
      th
        = t('checks.results.rule_id')
      th
        = t('checks.results.line:column')
  tbody
    == render partial: 'src_file', collection: @check.check_results, locals: { check: @check }

app/views/web/repositories/checks/_src_file.html.slim
tr
  td[colspan="3"]
    = link_to src_file['filePath'],
    "https://github.com/#{check.repository.full_name}/tree/#{check.commit_id}/bin/bundle"
- src_file['messages'].each do |message|
  tr
    td
      = message['message']
    td
      = message['ruleId']
    td
      = "#{message['line']}:#{message['column']}"

app/views/web/repositories/checks/show.html.slim
.m-4
  = link_to t('repositories.buttons.to_repo'), repository_path(@check.repository), class: 'btn btn-primary mb-4'

  h1 = "#{t('repositories.check_title')} #{@check.id}"

  hr

  == render 'check_details'

app/views/web/repositories/index.html.slim
.m-4
  = link_to t('repositories.buttons.new'), new_repository_path, class: 'btn btn-primary'

  table.table.table-hover.mt-3
    thead
      tr
        th = t('repositories.table.header.name')
        th = t('repositories.table.header.language')
        th = t('repositories.table.header.status')
    tbody
      - @repositories&.each do |repository|
        - last_check = repository.checks.finished.last
        tr
          td = repository.name.present? ? link_to(repository.name, repository) : '-'
          td = repository.language
          td
            - if last_check.nil?
              = t('repositories.check.no_checks_yet')
            - elsif last_check.pending?
              = t('repositories.check.verification_not_completed_yet')
            - else
              = last_check.passed

app/views/web/repositories/new.html.slim
.m-4
  .mb-4
    == render partial: 'form', locals: { repository: @repository, repositories: @repositories }

app/views/web/repositories/show.html.slim
.m-4
  .mb-4
    h1 = @repository.full_name

  = link_to t('repositories.buttons.check'), repository_checks_path(@repository),
  data: { turbo_method: :post }, class: 'btn btn-primary mb-4'
  p
    strong.me-2 = t('repositories.attributes.name')
    = @repository.full_name
  p
    strong.me-2 = t('repositories.attributes.language')
    = @repository.language
  p
    strong.me-2 = t('repositories.attributes.created_at')
    = l(@repository.created_at, format: :long)
  p
    strong.me-2 = t('repositories.attributes.updated_at')
    = l(@repository.updated_at, format: :long)
  hr
  - if @repository.checks.any?
    table.table.table-striped
      thead
        tr
          th = ''
          th = t('checks.table.header.state')
          th = t('checks.table.header.commit_id')
          th = t('checks.table.header.is_passed')
          th = t('checks.table.header.created_at')
      tbody
        == render partial: 'check', collection: @repository.checks.order(created_at: :desc),
        locals: { repository_full_name: @repository.full_name }

app/views/web/welcome/index.html.slim
h2.mt-4.px-4
  = t('welcome.title')
p.mb-4.px-4
  = t('welcome.body')